In [5]:
import os
import pandas as pd
import numpy as np

In [6]:
file_path = "../../data/raw/CAR DETAILS FROM CAR DEKHO.xlsx"
car = pd.read_excel(file_path)
car

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [7]:
car.shape

(4340, 8)

In [8]:
car.columns.to_list()

['name',
 'year',
 'selling_price',
 'km_driven',
 'fuel',
 'seller_type',
 'transmission',
 'owner']

In [9]:
car.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [10]:
car.dtypes

name               str
year             int64
selling_price    int64
km_driven        int64
fuel               str
seller_type        str
transmission       str
owner              str
dtype: object

In [11]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   str
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   str
 5   seller_type    4340 non-null   str
 6   transmission   4340 non-null   str
 7   owner          4340 non-null   str
dtypes: int64(3), str(5)
memory usage: 515.2 KB

In [ ]:
print(car.select_dtypes(include=["int64","float64"]).head())
print(car.select_dtypes(include=["str"]).head())

   year  selling_price  km_driven
0  2007          60000      70000
1  2007         135000      50000
2  2012         600000     100000
3  2017         250000      46000
4  2014         450000     141000
                       name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner

In [13]:
print(car.idxmax())
print("no.of missing values:\n",car.isna().sum())
print("no.of duplicated rows:",car.duplicated().sum())

name             2865
year              158
selling_price    3872
km_driven        1243
fuel                0
seller_type       540
transmission        0
owner              44
dtype: int64
no.of missing values:
 name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64
no.of duplicated rows: 763

In [14]:
# Data exploration
car.name.isna().sum()

np.int64(0)

In [15]:
print(car.year.describe())
print(car.year.unique())
print("no.of missing values:",car.year.isna().sum())
print("Data type:",car.year.dtype)

count    4340.000000
mean     2013.090783
std         4.215344
min      1992.000000
25%      2011.000000
50%      2014.000000
75%      2016.000000
max      2020.000000
Name: year, dtype: float64
[2007 2012 2017 2014 2016 2015 2018 2019 2013 2011 2010 2009 2006 1996
 2005 2008 2004 1998 2003 2002 2020 2000 1999 2001 1995 1997 1992]
no.of missing values: 0
Data type: int64

In [16]:
print(car.selling_price.head())
print("no .of missing values:",car.selling_price.isna().sum())
print("Data type:",car.selling_price.dtype)
print("Total selling price:",car.selling_price.sum())

0     60000
1    135000
2    600000
3    250000
4    450000
Name: selling_price, dtype: int64
no .of missing values: 0
Data type: int64
Total selling price: 2187912533

In [17]:
print(car.km_driven.head())
print(car.km_driven.describe())

0     70000
1     50000
2    100000
3     46000
4    141000
Name: km_driven, dtype: int64
count      4340.000000
mean      66215.777419
std       46644.102194
min           1.000000
25%       35000.000000
50%       60000.000000
75%       90000.000000
max      806599.000000
Name: km_driven, dtype: float64

In [18]:
d_continuous = car.select_dtypes(include=("int64","float64"))
print(d_continuous.describe())
print(d_continuous.isna().sum())

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000
year             0
selling_price    0
km_driven        0
dtype: int64

In [19]:
d_categorical = car.select_dtypes(include=("str"))
d_categorical.head()

                       name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner

In [20]:
d_categorical.describe()

                          name    fuel seller_type transmission        owner
count                     4340    4340        4340         4340         4340
unique                    1491       5           3            2            5
top     Maruti Swift Dzire VDI  Diesel  Individual       Manual  First Owner
freq                        69    2153        3244         3892         2832

In [21]:
print("no of missing values:\n",d_categorical.isna().sum())
print("no.of duplicated values:",d_categorical.duplicated().sum())
print(d_categorical.fuel.unique())
print(d_categorical.owner.unique())

no of missing values:
 name            0
fuel            0
seller_type     0
transmission    0
owner           0
dtype: int64
no.of duplicated values: 2104
<ArrowStringArray>
['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric']
Length: 5, dtype: str
<ArrowStringArray>
[         'First Owner',         'Second Owner', 'Fourth & Above Owner',
          'Third Owner',       'Test Drive Car']
Length: 5, dtype: str

In [ ]:
print(car["owner"].value_counts())
print(car["owner"].isna().sum())
print(car['owner'].duplicated().sum())

owner
First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: count, dtype: int64
0
4335

In [32]:
print(car["fuel"].head())
print(car["fuel"].unique().tolist())
print(car["fuel"].value_counts())

0    Petrol
1    Petrol
2    Diesel
3    Petrol
4    Diesel
Name: fuel, dtype: str
['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric']
fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64

In [40]:
print(car["seller_type"].head())
print(car["seller_type"].unique().tolist())
print(car["seller_type"].dtype)
print(car["seller_type"].value_counts())

0    Individual
1    Individual
2    Individual
3    Individual
4    Individual
Name: seller_type, dtype: str
['Individual', 'Dealer', 'Trustmark Dealer']
str
seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [47]:
print(car["transmission"].head())
print(car["transmission"].unique().tolist())
print("no.of missing values:",car["transmission"].isna().sum())

0    Manual
1    Manual
2    Manual
3    Manual
4    Manual
Name: transmission, dtype: str
['Manual', 'Automatic']
no.of missing values: 0

In [48]:
import seaborn as sns
import matplotlib.pyplot as plt

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 were given