In [24]:
import pandas as pd
import numpy as np

In [25]:
file_path = "../../data/interim/cleaned_car.xlsx"
car = pd.read_excel(file_path)
car

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
3572,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
3573,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
3574,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
3575,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
3576,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [26]:
car.shape

(3577, 8)

In [27]:
car.isna().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [28]:
car.duplicated().sum()

np.int64(0)

In [29]:
car.select_dtypes(include="str")

,name,fuel,seller_type,transmission,owner
0,Maruti 800 AC,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...
3572,Hyundai i20 Magna 1.4 CRDi (Diesel),Diesel,Individual,Manual,Second Owner
3573,Hyundai i20 Magna 1.4 CRDi,Diesel,Individual,Manual,Second Owner
3574,Maruti 800 AC BSIII,Petrol,Individual,Manual,Second Owner
3575,Hyundai Creta 1.6 CRDi SX Option,Diesel,Individual,Manual,First Owner
3576,Renault KWID RXT,Petrol,Individual,Manual,First Owner

In [30]:
car = pd.get_dummies(car, columns=["fuel"], dtype="int")
car.head()

,name,year,selling_price,km_driven,seller_type,transmission,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol
0,Maruti 800 AC,2007,60000,70000,Individual,Manual,First Owner,0,0,0,0,1
1,Maruti Wagon R LXI Minor,2007,135000,50000,Individual,Manual,First Owner,0,0,0,0,1
2,Hyundai Verna 1.6 SX,2012,600000,100000,Individual,Manual,First Owner,0,1,0,0,0
3,Datsun RediGO T Option,2017,250000,46000,Individual,Manual,First Owner,0,0,0,0,1
4,Honda Amaze VX i-DTEC,2014,450000,141000,Individual,Manual,Second Owner,0,1,0,0,0

In [31]:
car["seller_type"].unique().tolist()

['Individual', 'Dealer', 'Trustmark Dealer']

In [32]:
car = pd.get_dummies(car,columns=["seller_type"], dtype="int")
car.head()

,name,year,selling_price,km_driven,transmission,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer
0,Maruti 800 AC,2007,60000,70000,Manual,First Owner,0,0,0,0,1,0,1,0
1,Maruti Wagon R LXI Minor,2007,135000,50000,Manual,First Owner,0,0,0,0,1,0,1,0
2,Hyundai Verna 1.6 SX,2012,600000,100000,Manual,First Owner,0,1,0,0,0,0,1,0
3,Datsun RediGO T Option,2017,250000,46000,Manual,First Owner,0,0,0,0,1,0,1,0
4,Honda Amaze VX i-DTEC,2014,450000,141000,Manual,Second Owner,0,1,0,0,0,0,1,0

In [33]:
print(car["owner"].unique().tolist())
print(car["owner"].value_counts())
car["owner"] = car["owner"].replace("Test Drive Car", np.nan)

['First Owner', 'Second Owner', 'Fourth & Above Owner', 'Third Owner', 'Test Drive Car']
owner
First Owner             2218
Second Owner             978
Third Owner              289
Fourth & Above Owner      75
Test Drive Car            17
Name: count, dtype: int64

In [34]:
car = car.dropna(subset=["owner"])
car["owner"].value_counts()

owner
First Owner             2218
Second Owner             978
Third Owner              289
Fourth & Above Owner      75
Name: count, dtype: int64

In [35]:
owner_mapping = {
    "First Owner" : 1,
    "Second Owner" : 2,
    "Third Owner" : 3,
    "Fourth & Above Owner": 4
}

car["owner"] = car["owner"].map(owner_mapping)

In [36]:
car["owner"].value_counts()

owner
1    2218
2     978
3     289
4      75
Name: count, dtype: int64

In [37]:
car = pd.get_dummies(car, columns=["transmission"], dtype="int")

In [38]:
car.head()

,name,year,selling_price,km_driven,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
0,Maruti 800 AC,2007,60000,70000,1,0,0,0,0,1,0,1,0,0,1
1,Maruti Wagon R LXI Minor,2007,135000,50000,1,0,0,0,0,1,0,1,0,0,1
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,0,1,0,0,0,0,1,0,0,1
3,Datsun RediGO T Option,2017,250000,46000,1,0,0,0,0,1,0,1,0,0,1
4,Honda Amaze VX i-DTEC,2014,450000,141000,2,0,1,0,0,0,0,1,0,0,1

In [39]:
car.to_excel("../../data/interim/transformed_car.xlsx",index=False)